// <auto-generated />
using System;
using AIAudioTalesServer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AIAudioTalesServer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231109201837_partsaddedd")]
    partial class partsaddedd
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AIAudioTalesServer.Models.Answer", b =>
                {
                    b.Property<int>("AnswerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AnswerId"), 1L, 1);

                    b.Property<string>("AnswerText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CurrentPartId")
                        .HasColumnType("int");

                    b.Property<int?>("NextPartId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("AnswerId");

                    b.HasIndex("CurrentPartId");

                    b.HasIndex("NextPartId")
                        .IsUnique();

                    b.ToTable("Answers");
                });

            modelBuilder.Entity("AIAudioTalesServer.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("BookCategory")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("ImageData")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("AIAudioTalesServer.Models.Part", b =>
                {
                    b.Property<int>("PartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PartId"), 1L, 1);

                    b.Property<string>("PartAudioAWSLink")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PartText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StoryId")
                        .HasColumnType("int");

                    b.HasKey("PartId");

                    b.HasIndex("StoryId");

                    b.ToTable("Parts");
                });

            modelBuilder.Entity("AIAudioTalesServer.Models.PurchasedBooks", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<int>("Language")
                        .HasColumnType("int");

                    b.Property<int>("PurchaseType")
                        .HasColumnType("int");

                    b.HasKey("UserId", "BookId");

                    b.HasIndex("BookId");

                    b.ToTable("PurchasedBooks");
                });

            modelBuilder.Entity("AIAudioTalesServer.Models.RefreshToken", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("AIAudioTalesServer.Models.Story", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.ToTable("Stories");
                });

            modelBuilder.Entity("AIAudioTalesServer.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AIAudioTalesServer.Models.Answer", b =>
                {
                    b.HasOne("AIAudioTalesServer.Models.Part", "CurrentPart")
                        .WithMany("Answers")
                        .HasForeignKey("CurrentPartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AIAudioTalesServer.Models.Part", "NextPart")
                        .WithOne("ParentAnswer")
                        .HasForeignKey("AIAudioTalesServer.Models.Answer", "NextPartId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CurrentPart");

                    b.Navigation("NextPart");
                });

            modelBuilder.Entity("AIAudioTalesServer.Models.Part", b =>
                {
                    b.HasOne("AIAudioTalesServer.Models.Story", "Story")
                        .WithMany("Parts")
                        .HasForeignKey("StoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Story");
                });

            modelBuilder.Entity("AIAudioTalesServer.Models.PurchasedBooks", b =>
                {
                    b.HasOne("AIAudioTalesServer.Models.Book", "Book")
                        .WithMany("PurchasedBooks")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AIAudioTalesServer.Models.User", "User")
                        .WithMany("PurchasedBooks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AIAudioTalesServer.Models.RefreshToken", b =>
                {
                    b.HasOne("AIAudioTalesServer.Models.User", "User")
                        .WithOne("RefreshToken")
                        .HasForeignKey("AIAudioTalesServer.Models.RefreshToken", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AIAudioTalesServer.Models.Story", b =>
                {
                    b.HasOne("AIAudioTalesServer.Models.Book", "Book")
                        .WithMany("Stories")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("AIAudioTalesServer.Models.Book", b =>
                {
                    b.Navigation("PurchasedBooks");

                    b.Navigation("Stories");
                });

            modelBuilder.Entity("AIAudioTalesServer.Models.Part", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("ParentAnswer")
                        .IsRequired();
                });

            modelBuilder.Entity("AIAudioTalesServer.Models.Story", b =>
                {
                    b.Navigation("Parts");
                });

            modelBuilder.Entity("AIAudioTalesServer.Models.User", b =>
                {
                    b.Navigation("PurchasedBooks");

                    b.Navigation("RefreshToken")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
